### ISSUE TITLE
invalid format '%.0f'; use format %s for character objects

### ISSUE THREAD

**Issue by Karel-Kroeze** [bwlewis/doRedis#23]
The latest versions of rredis change the default return value for some functions. This breaks doRedis.

From the rredis package;
>options('redis:num'=TRUE) Set this option to TRUE to return Redis : messages as numeric values.     This was the default behavior of the rredis package for all versions prior to 1.6.9. For versions of the R package later than that, redis : messages are returned as raw Redis string values to correspond to the data types stored in Redis. Set this option to revert to the old behavior.

>Redis commands affected by this option importantly include the increment and decrement operations.

The fix is simple (see above), but it would be nice if doRedis would work out of the box.

**Comment by Karel-Kroeze** [comment]
And I literally just realized that you're also the author of rredis... Thanks for making a great set of packages!

**Comment by bwlewis** [comment]
Thanks!

I'm just starting to work through a pretty complete re-write of doRedis. There are some serious open issues, and the ambitious changes I made in the last major update have not worked out so well in practice.

My plan is to revert to a simpler pull-based scheme similar to eariler versions of this package without so many bells and whistles, but taking advantage of some more recent changes in rredis. And I will be sure to fix this issue as part of that.

I expect to get new code up here sometime the week of 27 July.

**Comment by bwlewis** [comment]
This should be fixed in the 1.2.0 version/commit 4e01f7d9085f3e3d300c741dafd3fd1f4ca9ddc0
