### ISSUE TITLE
options('redis:num'=TRUE) has to be used

### ISSUE THREAD

**Issue by andreyto** [bwlewis/doRedis#25]
Otherwise, running example foreach loop returns an error:
```
> foreach(j=1:10,.combine=sum,.multicombine=TRUE) %dopar%
+     4*sum((runif(1000000)^2 + runif(1000000)^2)<1)/10000000
Error in sprintf("%s:%.0f.env", queue, ID) : 
  invalid format '%.0f'; use format %s for character objects
```
The error is generated inside `redisWorker()` function.
Maybe the documentation can be updated to require options() call?

**Comment by andreyto** [comment]
I see that this has been already changed in current Github code. I was using the version from CRAN.

**Comment by bwlewis** [comment]
Thanks, yes I'll try to get the dev version submitted to CRAN this week.
