### ISSUE TITLE
Allow forks on doRedis workers

### ISSUE THREAD

**Issue by drknexus** [bwlewis/doRedis#31]
I see the recently added warnings about forks on doRedis workers.  What is the nature of the issue?  If it is tractable, can it be resolved, and if so, broadly what would one need to look at to figure out the nature of the problem/identify potential solutions.

**Comment by bwlewis** [comment]
It can be used in some cases, but in my experience often leads to problems through no fault of Redis/doRedis. This is simply a fork issue. I expanded the caution in the README.md file to discuss this in a bit more detail. I also removed the warning in the code, in favor of just the clear caveat in the README.

In particular, I keep forgetting about this and then often get screwed up by BLAS libraries--in particular the AMD ACML library never works with fork (completely independently of doRedis). Worse, versions 10.x of the Intel MKL BLAS silently returned wrong results when used in forked processes!

Anyway, not a fan of fork-based parallelism in R...too many gotchas. I do agree that when it works, it's really nice and efficient. One just needs to be very wary of it...

**Comment by drknexus** [comment]
Okay, so then the issue is that the forked processes are reusing the same connection object as the worker session they forked from?  I can see how that would be a problem unless you could detect you were on a fork and rebuild the connection.  I've definitely run into the connection based gotchas - sorry for going a bit off topic, but do you know of a resource that discusses other gotchas?

**Comment by bwlewis** [comment]
See page 2 of Steve's vignette:

https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf

for a generic warning about doParallel and fork without exec (although not talking explicitly about math libraries).



Here is an informative, but _long_ discussion by OpenBlas maintainers about this.

https://github.com/xianyi/OpenBLAS/issues/294

See also a proposed general Gnu OpenMP work-around that will not be merged:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60035

The upshot is OpenMP + fork without exec is likely not valid. This can affect some libraries (AMD ACML, see below) even when OMP_NUM_THREADS=1. MKL and openblas seem to be more robust, in that order.

See the following example that has a lot of notes inside it. The key thing there is that an LAPACK call is made prior to fork, and then again after fork (via mclapply). That is the pathology to watch out for with OpenMP.

I am finding R + recent openblas (version 0.2.12-1, GotoBLAS2 1.13/LAPACK 3.5.0-4) to be pretty robust when used with parallel/mclapply. I am not running into hanging or crashing at least in repeated runs of this simple test, even with very over-committed threads/cores (OMP_NUM_THREADS=8, mc.cores=8 on a machine with 8 physical cores).

AMD's latest ACML library seems to always hang when used with fork, even with OMP_NUM_THREADS=1.

R + Intel MKL 10.3, exhibits a bad wrong result bug with over-committed threads/cores. It sometimes
also hangs, but never so far with OMP_NUM_THREADS=1 (and the wrong result bug does not appear then either). MKL versions 11.x seem to have fixed this.

```r
# Save this file as mc.R
# Invoke this from a Linux shell with either:
# OMP_NUM_THREADS=1  R < mc.R
# OMP_NUM_THREADS=8  R < mc.R
# replacint '8' above with, for example, your number of physical CPU cores
# or even more to horribly over-commit resources.

library(parallel)
set.seed(1)
a = matrix(rnorm(10000),100)
# Calling BLAS/LAPACK routines prior to fork can cause problems for older
# versions of Goto BLAS/Openblas and AMD ACML libraries. Both can hang/crash
# even with OMP_NUM_THREADS=1 . Newer version of Openblas fix this. See
# https://github.com/xianyi/OpenBLAS/pull/343
# for a description of their work-around.  As of R + ACML version 6.0.6-13 
# (fairly recent), it still does not work with mclapply, even with
# OMP_NUM_THREADS=1.
d = svd(a)$d
# The value of x should be zero. Interestingly, unlike ACML or old Goto
# which hang or crash (when over committed or not), Intel MKL 10.3 has
# _worse_ behavior and returns wrong (non-zero) results (!!) without
# a hint of error.
x = sum(unlist(mclapply(1:1000,function(j) svd(a)$d - d, mc.cores=detectCores())))
print(x)
```
