### ISSUE TITLE
Error in Socket Connection

### ISSUE THREAD

**Issue by Coop197823** [bwlewis/doRedis#45]
my setup includes running redis-server-x64-3.2.100, Rtools33, and R-3.2.5 on windows 7(clients) and windows sever 2008 r2 (Server).  
In R, I start my workers on multiple machines through a series of batch files until they get to the  rscript that has the following code:  

```
#!/usr/local/bin/Rscript
   require('doRedis')
   redisWorker('jobs', host='SERVER-1', port=6379)
```

within R I am running:

```
library(doRedis)
registerDoRedis(queue="jobs", host= 'SERVER-1', port=6379)
options('redis:num'=TRUE)

```

for some reason the workers on all machines including the host (SERVER-1) end up timing out with this error:

> Connection(host, port, open = "a+b", blocking = TRUE, timeout = timeout) : 
>   cannot open the connection
> In addition: Warning message:
> In socketConnection(host, port, open = "a+b", blocking = TRUE, timeout = timeout) :
>   SERVER-1:6379 cannot be opened

when I run this code through the main r gui on the computer with the redis-server (SERVER-1):

```
library(doRedis)
registerDoRedis(queue="jobs", host= 'SERVER-1', port=6379)
options('redis:num'=TRUE)
```
and the workers:

```
#!/usr/local/bin/Rscript
   require('doRedis')
   redisWorker('jobs')
```
The workers start up fine and work perfectly.  

if I run the local workers as with the same rgui code as above;
```
#!/usr/local/bin/Rscript
   require('doRedis')
   redisWorker('jobs', host='SERVER-1', port=6379)
```
The workers timeout and stop working.

I have allowed redis-server through the firewall and opened the ports.  Not sure what else I am doing wrong.  Thanks!

**Comment by bwlewis** [comment]
Can you tell me:

```{r}
packageDescription("redis")
packageDescription("doRedis")
```

You might try installing the latest versions on GitHub for each of
those packages; if that works let me know--we need to get CRAN updated
at some point.

**Comment by Coop197823** [comment]
R version - 3.2.5
Redis version - Windows version x64-3.2.100
do Redis version - x64 1.2.0


I just did a fresh update and install to everything except r (as I have a few packages that only work with this version of r) 

I installed doRedis using: 

```
install.packages("devtools")
devtools::install_github("bwlewis/doRedis")

```
here i the text from the install within R:

> Downloading GitHub repo bwlewis/doRedis@master
> from URL https://api.github.com/repos/bwlewis/doRedis/zipball/master
> Installing doRedis
> "C:/PROGRA~1/R/R-32~1.5/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/ccooper/AppData/Local/Temp/Rtmp6397jC/devtools39b82c15268c/bwlewis-doRedis-e4c1a81" --library="C:/Program  \
>   Files/R/R-3.2.5/library" --install-tests 
> 
> * installing *source* package 'doRedis' ...
> ** libs
> gcc -m64 -I"C:/PROGRA~1/R/R-32~1.5/include" -DNDEBUG -DWin32  -D_R_  -D_WIN32_WINNT=0x0501    -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c alive.c -o alive.o
> In file included from C:/PROGRA~1/R/R-32~1.5/include/R.h:50:0,
>                  from alive.c:49:
> C:/PROGRA~1/R/R-32~1.5/include/R_ext/RS.h:45:0: warning: "ERROR" redefined [enabled by default]
> c:\rtools\gcc-4.6.3\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/wingdi.h:70:0: note: this is the location of the previous definition
> alive.c: In function 'tcpconnect':
> alive.c:106:7: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
> alive.c: In function 'sendall':
> alive.c:173:23: warning: 'n' may be used uninitialized in this function [-Wuninitialized]
> gcc -m64 -shared -s -static-libgcc -o doRedis.dll tmp.def alive.o -lWs2_32 -lMswsock -lAdvApi32 -luser32 -lkernel32 -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.5/bin/x64 -lR
> installing to C:/Program Files/R/R-3.2.5/library/doRedis/libs/x64
> ** R
> ** inst
> ** tests
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (doRedis)
> > library(doRedis)
> Loading required package: rredis
> Loading required package: foreach
> foreach: simple, scalable parallel programming from Revolution Analytics
> Use Revolution R for scalability, fault tolerance and more.
> http://www.revolutionanalytics.com
> Loading required package: iterators
> 
> 
>

**Comment by Coop197823** [comment]
I found [this](http://stackoverflow.com/questions/13491202/socket-connection-error-in-doredis-on-aws-ec2), and it seems that there may be a bug with teh timeout value.  I ran fix(redisConnect)  after I updated to r 3.3.2 and got this code:

```
function (host = "localhost", port = 6379, password = NULL, returnRef = FALSE, 
    nodelay = TRUE, timeout = 2678399L) 
{
    .redisEnv$current <- new.env()
    assign("pipeline", FALSE, envir = .redisEnv$current)
    con <- .openConnection(host = host, port = port, nodelay = nodelay, 
        timeout = timeout, envir = .redisEnv$current)
    if (!is.null(password)) 
        tryCatch(redisAuth(password), error = function(e) {
            cat(paste("Error: ", e, "\n"))
            .closeConnection(con)
            rm(list = "con", envir = .redisEnv$current)
        })
    tryCatch(.redisPP(), error = function(e) {
        cat(paste("Error: ", e, "\n"))
        .closeConnection(con)
        rm(list = "con", envir = .redisEnv$current)
    })
    if (returnRef) 
        return(.redisEnv$current)
    invisible()
}
```
Here is my packageDescription("doRedis")

```
Package: doRedis
Type: Package
Title: "Foreach" Parallel Adapter Using the "Redis" Database
Version: 1.2.0
Date: 2015-08-06
Author: B. W. Lewis <blewis@illposed.net>
Maintainer: B. W. Lewis <blewis@illposed.net>
Description: A parallel back end for the "foreach" package using the
        "Redis" database.
BugReports: https://github.com/bwlewis/doRedis/issues
Depends: R (>= 2.5), rredis (>= 1.7.0), foreach(>= 1.3.0), iterators(>=
        1.0.0), utils
Imports: parallel, stats
Suggests: knitr
VignetteBuilder: knitr
License: GPL-2
LazyLoad: yes
RoxygenNote: 5.0.0
Built: R 3.3.2; x86_64-w64-mingw32; 2017-02-09 20:19:09 UTC; windows
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: doRedis
RemoteUsername: bwlewis
RemoteRef: master
RemoteSha: e4c1a81aa6bd0e4bfba2a7b465f08f822fd8c0d3
GithubRepo: doRedis
GithubUsername: bwlewis
GithubRef: master
GithubSHA1: e4c1a81aa6bd0e4bfba2a7b465f08f822fd8c0d3

-- File: C:/Program Files/R/R-3.3.2/library/doRedis/Meta/package.rds 


```

Here is packageDescription("rredis")


```
Package: rredis
Type: Package
Title: "Redis" Key/Value Database Client
Version: 1.7.0
Date: 2015-07-04
Author: B. W. Lewis
Maintainer: B. W. Lewis <blewis@illposed.net>
Description: R client interface to the "Redis" key-value database.
License: Apache License (>= 2.0)
LazyLoad: yes
Suggests: RUnit
NeedsCompilation: yes
Packaged: 2015-07-05 14:12:41 UTC; blewis
Repository: CRAN
Date/Publication: 2015-07-05 23:37:49
Built: R 3.3.2; x86_64-w64-mingw32; 2016-11-11 02:17:33 UTC; windows

-- File: C:/Program Files/R/R-3.3.2/library/rredis/Meta/package.rds 
```

**Comment by Coop197823** [comment]
I uninstalled redis and installed the prior version of redis: Redis-x64-3.0.504 and it is working again.  One other thing to consider is that I do not think I had the path of the other version of redis in the environmental variables.  I will try that next

**Comment by bwlewis** [comment]
thanks for looking in to this, I'm investigating too

**Comment by bwlewis** [comment]
Fxed by the redux package dependency now in version 2.
