### ISSUE TITLE
startLocalWorkers() error in sink() when setting loglevel

### ISSUE THREAD

**Issue by tomastelensky** [bwlewis/doRedis#54]
startLocalWorkers() fails with an error when using the `loglevel` argument, even if it's kept at zero:

```
queue <- 'jobs'
server <- '10.0.67.4'
require(doRedis)
# doesn't matter whether or not I call `registerDoRedis(queue, server)` here
startLocalWorkers(2, queue, host = server, loglevel = 0)
```

Output:

> Error in sink(type = "message", file = log) :
>   'file' must be NULL or an already open connection
> Calls: redisWorker -> sink
> Execution halted
> Error in sink(type = "message", file = log) :
>   'file' must be NULL or an already open connection
> Calls: redisWorker -> sink
> Execution halted

It fails on Linux; on Windows I don't see an error there.

doRedis version 2.0.0, R version 3.6.0

**Comment by bwlewis** [comment]
Thanks, good catch. Should be fixed now. Version 2.0.1 will be on CRAN later this week.
